# Dockerfile-nginx
FROM nginx:mainline-alpine
# Nginx will listen on this port
EXPOSE 80
# Remove the default config file that
# /etc/nginx/nginx.conf includes
RUN rm /etc/nginx/conf.d/default.conf
COPY app.conf /etc/nginx/conf.d